lib/catcasts_web/router.ex
defmodule CatcastsWeb.Router do
  use CatcastsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Catcasts.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug CatcastsWeb.Plugs.RequireAuth
  end

  scope "/", CatcastsWeb do
    pipe_through [:browser, :auth]

    resources "/videos", VideoController, only: [:new, :create]
  end

  scope "/", CatcastsWeb do
    pipe_through :browser

    resources "/videos", VideoController, only: [:index, :show, :delete]
    get "/", PageController, :index
  end

  # for Google Auth
  scope "/auth", CatcastsWeb do
    pipe_through :browser

    get "/signout", AuthController, :delete
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :new
  end

end

lib/catcasts_web/views/layout_view.ex
defmodule CatcastsWeb.LayoutView do
  use CatcastsWeb, :view
end

lib/catcasts_web/templates/layout/_navigation.html.eex
<div class="title-bar" data-responsive-toggle="my-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="my-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>
<div class="top-bar" id="my-menu">
  <div class="top-bar-left">
    <ul class="menu">
      <li class="menu-text">Catcasts</li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <%= if @conn.assigns[:user] do %>
        <li class="menu-text">
          Welcome, <%= @conn.assigns.user.first_name %>!
        </li>
        <li>
          <%= link "Videos", to: video_path(@conn, :index) %>
        </li>
        <li>
          <%= link "Add Video", to: video_path(@conn, :new) %>
        </li>
        <li>
          <%= link "Sign out", to: auth_path(@conn, :delete), class: "button alert" %>
        </li>
      <% else %>
        <li>
          <%= link "Videos", to: video_path(@conn, :index) %>
        </li>
        <li>
          <%= link "Sign in with Google", to: auth_path(@conn, :request, "google", scope: "email profile"), class: "button" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

lib/catcasts_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Catcasts!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <%= render "_navigation.html", conn: @conn %>

      <p class="callout primary flash-alert" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="callout alert flash-alert" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>

    <script>
      $(document).foundation();
    </script>
  </body>
</html>